%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/fernandoquevedovallejo/Documents/GitHub/papers/graficas/newpaper/Dataset3_14_13_8.csv
%
% Auto-generated by MATLAB on 21-Apr-2021 20:52:41

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "C1", "C2", "C3", "P1", "V1", "A1", "P2", "V2", "A2", "P3", "V3", "A3", "O1", "O2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
NPaperData = readtable("/Users/fernandoquevedovallejo/Documents/GitHub/papers/graficas/newpaper/Dataset3_14_13_8.csv", opts);


%% Clear temporary variables
clear opts